#!/usr/bin/env python3
# discriminate.py -- CC0, stdlib only, no network, phone-buildable.
#
# The instrument measures itself. A question generated by
# aperture_scan is a HYPOTHESIS: "answering this differently leads to
# materially different implementations." Sounding intelligent is not
# evidence. This module is the test:
#
#   take one underspecified request
#   take one generated question
#   produce implementations under TWO different answer profiles
#   measure whether the artifacts diverge in meaningful ways
#
# If they do not diverge, the question DID NOT DISCRIMINATE, and that
# is recorded against the registry entry -- measurable evidence about
# the instrument itself, the same posture as the move-set
# garbage-ledger finding: the instrument's reward attacked by the
# instrument.
#
# WHAT COUNTS AS MEANINGFUL DIVERGENCE
#     Not formatting. For Python artifacts, both sides are normalized
#     through the AST (comments, docstrings, and whitespace removed) and
#     compared on their structural node multiset. For other text, on
#     the token multiset. divergence in [0,1] = 1 - similarity.
#     DISCRIMINATES requires divergence >= THRESHOLD.
#
# THE LIMIT, STATED HERE RATHER THAN AT THE BOTTOM
#     Structural divergence is a proxy. Two implementations can diverge
#     in structure and not in behavior (a loop vs a comprehension), and
#     can agree in structure and diverge in behavior (one constant
#     changed). This module reports UNMEASURABLE when either artifact
#     cannot be parsed or compared, and its DISCRIMINATES verdict is
#     about STRUCTURE, stated as such. A question can discriminate in
#     behavior without discriminating in structure; that false negative
#     is a property of this proxy, not of the question. The suite
#     shows both edges.
#
# usage:  python3 discriminate.py --artifacts a1.py a2.py [--json]
#         python3 discriminate.py --selftest

import ast
import json
import sys
from collections import Counter

THRESHOLD = 0.20  # below this, two artifacts are structurally the same
                  # implementation for the purposes of the question that
                  # was asked. Stated here, tunable at the call site,
                  # never hidden inside the verdict.

SCHEMA = "da-discrimination/1"


class Unmeasurable(Exception):
    pass


def _py_structure(text):
    """AST node multiset with comments/docstrings/whitespace removed."""
    try:
        tree = ast.parse(text)
    except SyntaxError as e:
        raise Unmeasurable("python artifact does not parse: %s" % e)
    nodes = Counter()
    for node in ast.walk(tree):
        nodes[type(node).__name__] += 1
        # constants carry behavior; fold their values in so a changed
        # constant is a divergence, not an invisible detail
        if isinstance(node, ast.Constant):
            nodes["Const:%r" % (node.value,)] += 1
        elif isinstance(node, ast.Name):
            nodes["Name:%s" % node.id] += 1
    return nodes


def _text_structure(text):
    tokens = Counter(text.lower().split())
    if not tokens:
        raise Unmeasurable("artifact has no comparable tokens")
    return tokens


def _structure(path):
    with open(path, encoding="utf-8", errors="replace") as fh:
        text = fh.read()
    if path.endswith(".py"):
        try:
            return _py_structure(text)
        except Unmeasurable:
            raise
    return _text_structure(text)


def divergence(path_a, path_b):
    """1 - weighted-Jaccard similarity of structural multisets."""
    sa = _structure(path_a)
    sb = _structure(path_b)
    keys = set(sa) | set(sb)
    if not keys:
        raise Unmeasurable("both structures empty")
    inter = sum(min(sa[k], sb[k]) for k in keys)
    union = sum(max(sa[k], sb[k]) for k in keys)
    return 1.0 - (inter / union if union else 1.0)


def measure(path_a, path_b, question=None, threshold=THRESHOLD):
    """The verdict. UNMEASURABLE is a return type, not an error."""
    try:
        d = divergence(path_a, path_b)
    except Unmeasurable as e:
        return {
            "schema": SCHEMA,
            "question": question,
            "result": "UNMEASURABLE",
            "divergence": None,
            "reason": str(e),
            "note": "unmeasurable is a property of this comparison, "
                    "not a verdict on the question",
        }
    verdict = "DISCRIMINATES" if d >= threshold else "DOES_NOT_DISCRIMINATE"
    return {
        "schema": SCHEMA,
        "question": question,
        "result": verdict,
        "divergence": round(d, 4),
        "threshold": threshold,
        "note": "verdict is about STRUCTURAL divergence (AST / token "
                "multiset), stated as such; behavioral divergence "
                "without structural divergence is this proxy's named "
                "false negative",
    }


def main(argv):
    args = argv[1:]
    if "--selftest" in args:
        import os
        import tempfile
        d = tempfile.mkdtemp()
        a = os.path.join(d, "a.py")
        b = os.path.join(d, "b.py")
        with open(a, "w") as fh:
            fh.write("def get(k):\n    return CACHE.get(k)\n")
        with open(b, "w") as fh:
            fh.write("import sqlite3\n"
                     "def get(k):\n"
                     "    cur = DB.execute('select v from t where k=?', (k,))\n"
                     "    return cur.fetchone()\n")
        r1 = measure(a, b, question="in-memory cache vs sqlite?")
        assert r1["result"] == "DISCRIMINATES", r1
        b2 = os.path.join(d, "b2.py")
        with open(b2, "w") as fh:
            fh.write("def get(k):  # fetch from cache\n"
                     "    '''return the cached value'''\n"
                     "    return CACHE.get(k)\n")
        r2 = measure(a, b2, question="cosmetic twin")
        assert r2["result"] == "DOES_NOT_DISCRIMINATE", r2
        print("selftest ok: profiles diverge (%.2f); cosmetic twins do "
              "not (%.2f)" % (r1["divergence"], r2["divergence"]))
        return 0
    if "--artifacts" in args:
        idx = args.index("--artifacts")
        a, b = args[idx + 1], args[idx + 2]
        q = args[args.index("--question") + 1] if "--question" in args \
            else None
        r = measure(a, b, question=q)
        print(json.dumps(r, indent=2) if "--json" in args else
              "%s (divergence %s, threshold %s)%s"
              % (r["result"], r.get("divergence"), r.get("threshold"),
                 (" -- " + r["note"]) if r["result"] == "UNMEASURABLE"
                 else ""))
        return 0 if r["result"] != "UNMEASURABLE" else 3
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
